### ISSUE TITLE
BoyerMyrvoldPlanarity fails with NullPointerException

### ISSUE THREAD

**Issue by nlskrg** [renatav/GraphDrawing#12]
For some graphs the implementation of the algorithm by Boyer and Myrvold fails with the following exception:

> Exception in thread "main" java.lang.NullPointerException
	at graph.algorithms.planarity.BoyerMyrvoldPlanarity.walkdown(BoyerMyrvoldPlanarity.java:452)
	at graph.algorithms.planarity.BoyerMyrvoldPlanarity.processVertex(BoyerMyrvoldPlanarity.java:221)
	at graph.algorithms.planarity.BoyerMyrvoldPlanarity.isPlannar(BoyerMyrvoldPlanarity.java:153)

A test case to reproduce the error is attached:

[BoyerMyrvoldPlanarityTest.java.zip](https://github.com/renatav/GraphDrawing/files/566968/BoyerMyrvoldPlanarityTest.java.zip)

**Comment by renatav** [comment]
Fixed

**Comment by renatav** [comment]
Fixed, the test now has successful outcome.
